### PR TITLE
call pendingDestroy when add image

### PR DESCRIPTION
**Pull request by taoabc**
Call json.addToCache will call pendingDestroy internally, but add image to textureManager will not, so I call pendingDestroy manually.

### CODE REVIEW

**Comment by akdcl** [comment]
@jcyuan

**Comment by jcyuan** [comment]
👍 good catch, a potential bug of memory leak.
but we can just use `image.addToCache();` instead.
the old code should be a legacy problem made when immigrating to the new db file plugin.

**Comment by taoabc** [comment]
I don't recommend add this image to cache because we already add image to textureManager, will become more heavier. What do you think? :grin:

**Comment by jcyuan** [comment]
`image.addToCache`, this action actually does 2 things:
1, add the loaded image into the `textureManager` belongs to the `loader`. (global to scene)
2, call `pendingDestroy` to prepare to delete the stuffs created when loading the images

only a diffenent between them is, `addToCache` detects to see if the image to be loaded has a normal map or not, if it does, add to cache too.

so actually they are the same, but use Phaser's API is more sensible because you don't knwo whether they will be changed in the furture or not, right?

**Comment by taoabc** [comment]
You're right, I've changed to addToCache

**Comment by taoabc** [comment]
Sorry for misunderstand your suggest, fixed and refresh output files at newest commit.

**Comment by jcyuan** [comment]
thanks for your effort @taoabc 👍

**Pull request merged**
